from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)  # Allow cross-origin requests

@app.route('/chat', methods=['POST'])
def chat():
    user_input = request.json.get('message', '').lower()  # Convert input to lowercase

    # Categorized financial terms
    categories = {
        "financial ratios": [
            "Current ratio", "Quick ratio", "Debt to equity", "Dividend payout ratio", "ROI", "ROE", "P/E ratio", "Dividend yield"
        ],
        "financial statements": [
            "Balance sheet", "Income statement", "Cash flow statement"
        ],
        "valuation metrics": [
            "DCF", "NPV", "IRR", "WACC", "EV/EBITDA", "Enterprise value", "Terminal value"
        ],
        "cost analysis": [
            "Cost of equity", "Cost of debt", "Weighted average cost of capital (WACC)"
        ],
        "profitability metrics": [
            "Gross profit margin", "Net profit margin", "EBIT", "EBITDA", "Operating profit margin"
        ],
        "market analysis": [
            "Market capitalization", "Enterprise value", "Beta", "Market risk premium"
        ],
        "cash flow metrics": [
            "Operating cash flow", "Free cash flow (FCF)", "Net cash flow"
        ]
    }

    # Predefined financial terms and explanations
    financial_terms = {
        "dcf": "DCF (Discounted Cash Flow) is a valuation method used to estimate the value of an investment based on its expected future cash flows.",
        "irr": "IRR (Internal Rate of Return) is the discount rate that makes the net present value (NPV) of all cash flows from a project equal to zero.",
        "npv": "NPV (Net Present Value) is the difference between the present value of cash inflows and outflows over a period of time.",
        "wacc": "WACC (Weighted Average Cost of Capital) is the average rate of return a company is expected to pay its investors to finance its assets.",
        "current ratio": "The Current Ratio measures a company's ability to pay short-term obligations with short-term assets.",
        "quick ratio": "The Quick Ratio (Acid-Test Ratio) measures a company's ability to meet short-term obligations with its most liquid assets.",
        "gross profit margin": "Gross Profit Margin is a profitability ratio that shows the percentage of revenue that exceeds the cost of goods sold (COGS).",
        "net profit margin": "Net Profit Margin is the percentage of profit a company makes for every dollar of revenue after accounting for all expenses.",
        "beta": "Beta measures the volatility or risk of a stock relative to the overall market.",
        "enterprise value": "Enterprise Value (EV) is a measure of a company's total value, including market cap, debt, minority interest, and cash.",
        "market capitalization": "Market capitalization is the total value of a company’s outstanding shares, calculated as share price multiplied by the number of shares outstanding.",
        "free cash flow": "Free Cash Flow (FCF) is the cash a company generates after accounting for cash outflows to support operations and maintain capital assets.",
        "operating cash flow": "Operating Cash Flow is the cash generated by a company's normal operating activities, excluding financing and investing activities.",
        "ebitda": "EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization) is a metric used to evaluate a company's operating performance.",
        "ebit": "EBIT (Earnings Before Interest and Taxes) measures a company's profitability from operations, excluding the impact of financing and taxes.",
        "terminal value": "Terminal Value represents the value of a business at the end of a forecast period, commonly used in DCF analysis."
        # Add more terms as needed
    }

    # Check for category-based queries
    if "ratios" in user_input:
        response = f"Here are some financial ratios you can ask about: {', '.join(categories['financial ratios'])}"
    elif "statements" in user_input:
        response = f"Here are some financial statements you can ask about: {', '.join(categories['financial statements'])}"
    elif "valuation" in user_input:
        response = f"Here are some valuation metrics you can ask about: {', '.join(categories['valuation metrics'])}"
    elif "cost" in user_input:
        response = f"Here are some cost analysis metrics you can ask about: {', '.join(categories['cost analysis'])}"
    elif "profitability" in user_input:
        response = f"Here are some profitability metrics you can ask about: {', '.join(categories['profitability metrics'])}"
    elif "cash flow" in user_input:
        response = f"Here are some cash flow metrics you can ask about: {', '.join(categories['cash flow metrics'])}"
    elif "market" in user_input:
        response = f"Here are some market analysis metrics you can ask about: {', '.join(categories['market analysis'])}"
    else:
        # Match specific terms
        for term in financial_terms:
            if term in user_input:
                response = financial_terms[term]
                break
        else:
            response = "I'm not sure what that means. Could you try rephrasing or ask about something else?"

    return jsonify({"response": response})


if __name__ == "__main__":
    app.run(debug=True, port=5001)
